# Generated by Django 6.0 on 2026-04-17 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('gender_probability', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sample_size', models.PositiveIntegerField()),
                ('age', models.PositiveSmallIntegerField()),
                ('age_group', models.CharField(choices=[('child', 'Child'), ('teenager', 'Teenager'), ('adult', 'Adult'), ('senior', 'Senior')], max_length=10)),
                ('country_id', models.CharField(max_length=5)),
                ('country_probability', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
